# Generated by Django 5.1.3 on 2024-11-14 11:42

import utils.get_image_filename
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelsystem', '0006_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=utils.get_image_filename.get_image_filename),
        ),
    ]
