# Generated by Django 5.0.6 on 2024-09-17 10:49

import utils.get_image_filename
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, upload_to=utils.get_image_filename.get_image_filename),
        ),
    ]
