# Generated by Django 5.0.6 on 2024-09-17 11:29

import utils.get_image_filename
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelsystem', '0002_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=utils.get_image_filename.get_image_filename),
        ),
    ]
