# Generated by Django 5.0.6 on 2024-09-17 11:29

import utils.get_image_filename
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelinfo', '0002_partner_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to=utils.get_image_filename.get_image_filename),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(upload_to='static/partner_logos/'),
        ),
    ]
