# Generated by Django 5.0.6 on 2024-09-17 10:49

import utils.get_image_filename
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='')),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to=utils.get_image_filename.get_image_filename),
        ),
    ]
